@startuml
hide circle
skinparam linetype ortho


entity Pais {
  pai_id : int <<PK>>
  --
  pai_nombre : nvarchar(255)
}

entity Provincia {
  pro_id : int <<PK>>
  --
  pro_pais : int <<FK>>
  pro_nombre : nvarchar(255)
}

entity Localidad {
  loc_id : bigint <<PK>>
  --
  loc_provincia : int <<FK>>
  loc_nombre : nvarchar(255)
}

entity Alianza {
  ali_id : int <<PK>>
  --
  ali_descripcion : nvarchar(255)
}

entity Estado_Propuesta {
  esp_id : int <<PK>>
  --
  esp_descripcion : nvarchar(255)
}

entity Agencia {
  age_nro_agencia : int <<PK>>
  age_localidad : bigint <<FK>>
  --
  age_descripcion nvarchar(255)
  age_direccion nvarchar(255)
  age_telefono nvarchar(50)
  age_mail nvarchar(255)
}

entity Cliente {
  cli_id : bigint <<PK>>
  cli_localidad : bigint <<FK>>
  --
  cli_dni : nvarchar(20)
  cli_nombre : nvarchar(255)
  cli_apellido : nvarchar(255)
  cli_fecha_nacimiento : date
  cli_mail : nvarchar(255)
  cli_telefono : nvarchar(50)
  cli_direccion : nvarchar(255)
}

entity Agente {
  agt_legajo : bigint <<PK>>
  agt_localidad : bigint <<FK>>
  --
  agt_agencia : int <<FK>>
  agt_dni : nvarchar(20)
  agt_nombre : nvarchar(255)
  agt_apellido : nvarchar(255)
  agt_fecha_nacimiento : date
  agt_mail : nvarchar(255)
  agt_telefono : nvarchar(50)
  agt_direccion : nvarchar(255)
}

entity CanalVenta {
  cdv_id : int <<PK>>
  --
  cdv_descripcion : nvarchar(255)
}

entity MedioPago {
  mdp_id : int <<PK>>
  --
  mdp_descripcion : nvarchar(255)
}

entity Aerolinea {
  aero_codigo : nvarchar(10) <<PK>>
  --
  aero_nombre : nvarchar(255)
  aero_pais : int <<FK>>
  aero_alianza : int <<FK>>
}

entity Aeropuerto {
  aer_codigo : nvarchar(10) <<PK>>
  --
  aer_descripcion : nvarchar(255)
  aer_ciudad : bigint <<FK>>
}

entity Vuelo {
  vue_id : bigint <<PK>>
  --
  vue_aerolinea : nvarchar(10) <<FK>>
  vue_aeropuerto_llegada : nvarchar(10) <<FK>>
  vue_aeropuerto_salida : nvarchar(10) <<FK>>
  vue_fecha_salida : date
  vue_fecha_llegada : date
  vue_hora_salida : time
  vue_hora_llegada : time
  vue_incluye_carry : bit
  vue_incluye_valija : bit
  vue_duracion : int
}

entity Hospedaje {
  hos_id : bigint <<PK>>
  --
  hos_nombre : nvarchar(255)
  hos_direccion : nvarchar(255)
  hos_horario_checkin : time
  hos_horario_checkout : time
  hos_ciudad : bigint <<FK>>
  hos_incluye_desayuno : bit
}

entity Tipo_de_habitacion {
  tdp_id : bigint <<PK>>
  --
  tdp_descripcion : nvarchar(255)
  tdp_cant_camas : int
  tdp_precio_base : decimal(18,2)
  tdp_hospedaje : : bigint <<FK>>
}

entity Proveedor_Excursion {
  pre_id : bigint <<PK>>
  --
  pre_nombre : nvarchar(255)
  pre_mail : nvarchar(255)
  pre_telefono : nvarchar(50)
}

entity Excursion {
  exc_id : bigint <<PK>>
  --
  exc_proveedor : bigint <<FK>>
  exc_nombre : nvarchar(255)
  exc_descripcion : nvarchar(max)
  exc_duracion : int
  exc_horario : time
  exc_precio : decimal(18,2)
  exc_ciudad : bigint <<FK>>
}

entity Venta {
  ven_nro_venta : bigint <<PK>>
  --
  ven_cli : bigint <<FK>>
  ven_agente : bigint <<FK>>
  ven_cdv : int <<FK>>
  ven_medio_pago : int <<FK>>
  ven_fecha : date 
  ven_subtotal : decimal(18,2)
  ven_descuento : decimal(18,2)
  ven_total : decimal(18,2)
}

entity Venta_Vuelo {
  vv_id : bigint <<PK>>
  --
  vv_venta : bigint <<FK>>
  vv_vuelo : bigint <<FK>>
  vv_cant_pasaje : int
  vv_precio : decimal(18,2)
  vv_subtotal : decimal(18,2) 
  vv_codigo_reserva : nvarchar(255)
}

entity Venta_Hospedaje {
  vh_id : bigint <<PK>>
  --
  vh_venta : bigint <<FK>>
  vh_tipo_habitacion : bigint <<FK>>
  vh_fecha_desde : date
  vh_fecha_hasta : date
  vh_cantidad : int
  vh_precio : decimal(18,2)
  vh_subtotal : decimal(18,2)
  vh_codigo_reserva : nvarchar(255)
} 

entity Venta_Excursion {
  ve_id : bigint <<PK>>
  --
  ve_venta : bigint <<FK>>
  ve_excursion : bigint <<FK>>
  ve_fecha : date
  ve_cantidad : int
  ve_precio : decimal(18,2)
  ve_subtotal : decimal(18,2)
  ve_codigo_reserva : nvarchar(255)
}

entity Solicitud_Cotizacion {
  sol_nro : bigint <<PK>>
  --
  sol_cliente : bigint <<FK>>
  sol_agente : bigint <<FK>>
  sol_fecha_solicitud : date
  sol_fecha_inicio : date
  sol_fecha_fin : date
  sol_cant_pasajeros: int
  sol_presupuesto : decimal(18,2)
  sol_observaciones : nvarchar(max)
}

entity Detalle_Solicitud {
  ds_id : bigint <<PK>>
  --
  ds_solicitud : bigint <<FK>>
  ds_ciudad : bigint <<FK>>
  ds_cant_dias : int
  ds_observaciones : nvarchar(max)
}

entity Propuesta {
  prop_nro_propuesta : bigint <<PK>>
  --
  prop_solicitud : bigint <<FK>>
  prop_agente : bigint <<FK>>
  prop_estado : int <<FK>>
  prop_fecha : date
  prop_vigencia : date
  prop_fecha_desde : date
  prop_fecha_hasta : date
  prop_subtotal : decimal(18,2)
  prop_descuento : decimal(18,2)
  prop_total : decimal(18,2)
}

entity Propuesta_Vuelo {
  pv_id : bigint <<PK>>
  --
  pv_propuesta : bigint <<FK>>
  pv_vuelo : bigint <<FK>>
  pv_cantidad : int
  pv_precio : decimal(18,2)
  pv_subtotal : decimal(18,2)
}
  
entity Propuesta_Hospedaje {
  ph_id : bigint <<PK>>
  --
  ph_propuesta : bigint <<FK>>
  ph_tipo_habitacion : int <<FK>>
  ph_fecha_desde : date
  ph_fecha_hasta : date
  ph_cant_habitaciones : int
  ph_precio : decimal(18,2)
  ph_subtotal : decimal(18,2)
}

entity Encuesta {
  enc_id : bigint <<PK>>
  --
  enc_cliente : bigint <<FK>>
  enc_agente : bigint <<FK>>
  enc_fecha : date
  enc_comentario : nvarchar(max)
  enc_venta     : bigint <<FK>>
  enc_solicitud : bigint <<FK>>
}

entity Aspecto_Encuesta {
  asp_id : bigint <<PK>>
  --
  asp_descripcion : nvarchar(255)
}

entity Valoracion_Encuesta {
  val_id : bigint <<PK>>
  --
  val_encuesta : bigint <<FK>>
  val_aspecto : bigint <<FK>>
  val_puntaje : int
}

entity Ciudad {
  ciu_id : bigint <<PK>>
  --
  ciu_nombre : nvarchar(255)
  ciu_provincia : nvarchar(255)
}

Agencia ||--o{ Agente

Cliente ||--o{ Venta
Cliente ||--o{ Solicitud_Cotizacion
Cliente ||--o{ Encuesta

Agente ||--o{ Venta
Agente ||--o{ Solicitud_Cotizacion
Agente ||--o{ Propuesta
Agente ||--o{ Encuesta

Aerolinea ||--o{ Vuelo
Aeropuerto ||--o{ Vuelo
Aeropuerto ||--o{ Vuelo

Hospedaje ||--o{ Tipo_de_habitacion

Proveedor_Excursion ||--o{ Excursion

Venta ||--o{ Venta_Vuelo
Venta ||--o{ Venta_Hospedaje
Venta ||--o{ Venta_Excursion

Vuelo ||--o{ Venta_Vuelo
Tipo_de_habitacion ||--o{ Venta_Hospedaje
Excursion ||--o{ Venta_Excursion

Solicitud_Cotizacion ||--o{ Detalle_Solicitud
Solicitud_Cotizacion ||--o{ Propuesta

Propuesta ||--o{ Propuesta_Vuelo
Propuesta ||--o{ Propuesta_Hospedaje

Vuelo ||--o{ Propuesta_Vuelo
Tipo_de_habitacion ||--o{ Propuesta_Hospedaje

Encuesta ||--o{ Valoracion_Encuesta
Aspecto_Encuesta ||--o{ Valoracion_Encuesta

Ciudad ||--o{ Detalle_Solicitud

Pais ||--o{ Provincia

Provincia ||--o{ Localidad
Provincia ||--o{ Ciudad

Localidad ||--o{ Agencia
Localidad ||--o{ Cliente
Localidad ||--o{ Agente

Pais ||--o{ Aerolinea

Alianza ||--o{ Aerolinea

Ciudad ||--o{ Aeropuerto
Ciudad ||--o{ Hospedaje
Ciudad ||--o{ Excursion

Estado_Propuesta ||--o{ Propuesta

Venta ||--o{ Encuesta
Solicitud_Cotizacion ||--o{ Encuesta


@enduml
