@startuml
hide circle
skinparam linetype ortho

entity Agencia {
  age_nro_agencia : <<PK>>
  --
  age_descripcion
  age_direccion
  age_telefono
  age_mail
  age_localidad
  age_provincia
}

entity Cliente {
  cli_id : <<PK>>
  --
  cli_dni
  cli_nombre
  cli_apellido
  cli_fecha_nacimiento
  cli_mail
  cli_telefono
  cli_direccion
  cli_localidad
  cli_provincia
}

entity Agente {
  agt_legajo : <<PK>>
  --
  agt_agencia : <<FK>>
  agt_dni
  agt_nombre
  agt_apellido
  agt_fecha_nacimiento
  agt_mail
  agt_telefono
  agt_direccion
  agt_localidad
  agt_provincia
}

entity CanalVenta {
  cdv_id : <<PK>>
  --
  cdv_descripcion
}

entity MedioPago {
  mdp_id : <<PK>>
  --
  mdp_descripcion
}

entity Aerolinea {
  aero_id : <<PK>>
  --
  aero_nombre
}

entity Aeropuerto {
  id_aeropuerto : <<PK>>
  --
  codigo
  nombre
  ciudad
  pais
}

entity Vuelo {
  vue_id : <<PK>>
  --
  vue_aerolinea : <<FK>>
  vue_aeropuerto_llegada : <<FK>>
  vue_aeropuerto_salida : <<FK>>
  vue_fecha_salida
  vue_fecha_llegada
  vue_hora_salida
  vue_hora_llegada
}

entity Hospedaje {
  hos_id : <<PK>>
  --
  hos_nombre
  hos_direccion
  hos_horario_checkin
  hos_horario_checkout
  hos_ciudad: <<FK>>
  hos_incluye_desayuno
}

entity Tipo_de_habitacion {
  tdp_id : <<PK>>
  --
  tdp_descripcion
  tdp_cant_camas
  tdp_precio_base
  tdp_hospedaje : <<FK>>
}

entity Proveedor_Excursion {
  pre_id : <<PK>>
  --
  pre_nombre
  pre_mail
  pre_telefono
}

entity Excursion {
  exc_id : <<PK>>
  --
  exc_proveedor : <<FK>>
  exc_nombre
  exc_descripcion
  exc_duracion
  exc_horario
  exc_precio
  exc_ciudad
}

entity Venta {
  ven_nro_venta : <<PK>>
  --
  ven_agencia : <<FK>>
  ven_cli : <<FK>>
  ven_agente : <<FK>>
  ven_cdv : <<FK>>
  ven_medio_pago : <<FK>>
  ven_fecha
  ven_subtotal
  ven_descuento
  ven_total
  ven_propuesta : <<FK>>
}

entity Venta_Vuelo {
  vv_id : <<PK>>
  --
  vv_venta : <<FK>>
  vv_vuelo : <<FK>>
  vv_cant_pasaje
  vv_precio
  vv_subtotal
  vv_codigo_reserva
}

entity Venta_Hospedaje {
  vh_id : PK
  --
  vh_venta : <<FK>>
  vh_tipo_habitacion : <<FK>>
  vh_fecha_desde
  vh_fecha_hasta
  vh_cantidad
  vh_precio
  vh_subtotal
  vh_codigo_reserva
}

entity Venta_Excursion {
  ve_id : <<PK>>
  --
  ve_venta : <<FK>>
  ve_excursion : <<FK>>
  ve_fecha
  ve_cantidad
  ve_precio
  ve_subtotal
  ve_codigo_reserva
}

entity Solicitud_Cotizacion {
  sol_nro : bigint <<PK>>
  --
  sol_cliente : nvarchar(255) <<FK>>
  sol_agente : bigint <<FK>>
  sol_fecha_solicitud : date
  sol_fecha_inicio : date
  sol_fecha_fin : date
  sol_cant_pasajeros: int
  sol_presupuesto : decimal(18,2)
  sol_observaciones : nvarchar(max)
}

entity Detalle_Solicitud {
  ds_id : bigint <<PK>>
  --
  ds_solicitud : bigint <<FK>>
  ds_ciudad : bigint <<FK>>
  ds_cant_dias : int
  ds_observaciones : nvarchar(max)
}

entity Propuesta {
  prop_nro_propuesta : bigint <<PK>>
  --
  prop_solicitud : bigint <<FK>>
  prop_agente : bigint <<FK>>
  prop_estado : nvarchar(255)
  prop_fecha : date
  prop_vigencia : date
  prop_fecha_desde : date
  prop_fecha_hasta : date
  prop_subtotal : decimal(18,2)
  prop_descuento : decimal(18,2)
  prop_total : decimal(18,2)
}

entity Propuesta_Vuelo {
  pv_id : bigint <<PK>>
  --
  pv_propuesta : bigint <<FK>>
  pv_vuelo : bigint <<FK>>
  pv_cantidad : int
  pv_precio : decimal(18,2)
  pv_subtotal : decimal(18,2)
}
  
entity Propuesta_Hospedaje {
  ph_id : bigint <<PK>>
  --
  ph_propuesta : bigint <<FK>>
  ph_tipo_habitacion : int <<FK>>
  ph_fecha_desde : date
  ph_fecha_hasta : date
  ph_cant_habitaciones : int
  ph_precio : decimal(18,2)
  ph_subtotal : decimal(18,2)
}

entity Encuesta {
  enc_id : bigint <<PK>>
  --
  enc_cliente : bigint <<FK>>
  enc_agente : bigint <<FK>>
  enc_venta : bigint <<FK>>
  enc_propuesta : bigint <<FK>>
  enc_fecha : date
  enc_comentario : nvarchar(max)
}

entity Aspecto_Encuesta {
  asp_id : bigint <<PK>>
  --
  asp_descripcion : nvarchar(255)
}

entity Valoracion_Encuesta {
  val_id : bigint <<PK>>
  --
  val_encuesta : bigint <<FK>>
  val_aspecto : bigint <<FK>>
  val_puntaje : int
}

Agencia ||--o{ Agente
Agencia ||--o{ Venta

Cliente ||--o{ Venta
Cliente ||--o{ Solicitud_Cotizacion
Cliente ||--o{ Encuesta

Agente ||--o{ Venta
Agente ||--o{ Solicitud_Cotizacion
Agente ||--o{ Propuesta
Agente ||--o{ Encuesta

CanalVenta ||--o{ Venta
MedioPago ||--o{ Venta

Aerolinea ||--o{ Vuelo
Aeropuerto ||--o{ Vuelo

Hospedaje ||--o{ Tipo_de_habitacion

Proveedor_Excursion ||--o{ Excursion

Venta ||--o{ Venta_Vuelo
Venta ||--o{ Venta_Hospedaje
Venta ||--o{ Venta_Excursion

Vuelo ||--o{ Venta_Vuelo
Tipo_de_habitacion ||--o{ Venta_Hospedaje
Excursion ||--o{ Venta_Excursion

Solicitud_Cotizacion ||--o{ Detalle_Solicitud
Solicitud_Cotizacion ||--o{ Propuesta

Propuesta ||--o{ Propuesta_Vuelo
Propuesta ||--o{ Propuesta_Hospedaje

Vuelo ||--o{ Propuesta_Vuelo
Tipo_de_habitacion ||--o{ Propuesta_Hospedaje

Propuesta ||--o{ Venta

Encuesta ||--o{ Valoracion_Encuesta
Aspecto_Encuesta ||--o{ Valoracion_Encuesta

Venta ||--o{ Encuesta
Propuesta ||--o{ Encuesta


@enduml
